### ISSUE TITLE
grid-layout-styles-concern

### ISSUE THREAD

**Issue by fafcrumb** [unicef/etools-partnership-management#15]
I'm still unfortunately missing the point of this file. The point is to avoid excess css, but the include="" attribute of the style tag allows you to only select and mixin the portions of iron-layout-classes you want. This of course still leaves a bit of unused css, but as grid-layout-styles grows, there could end up being even more waste there.

I'm not asking for a change/removal though, I can see it's already used a lot in @adi130987 code, but I'd need a stronger use case for using it myself.

**Comment by adi130987** [comment]
I created this file to be used when you need to display content on columns. In most cases the content of our app should be displayed on max 4 columns and this file can help you with that and and not duplicate the css. Also, you have horizontal, vertical and flex support used to organize your columns. I do not think this file will grow with more than 2 or 3 classes.
