### ISSUE TITLE
Fix app behaviors

### ISSUE THREAD

**Issue by adi130987** [unicef/etools-partnership-management#17]
Update etools-dialog behavior use  in app-behaviors. Add all app specific behaviors on a window object etoolsPmpBehaviors. For now we only have  RepeatableDataSetsBehavior and this will be available with etoolsPmpBehaviors.RepeatableDataSetsBehavior.

**Comment by adi130987** [comment]
We need to merge #18 asap. Partner details page assessments and staff members won't work without this.

**Comment by fafcrumb** [comment]
@adi130987 I have this fix on feature--partners-list branch. That branch is long overdue for a merge, so if we could simply merge that in I'd be happy. It's in there as pmpBehaviors.

**Comment by adi130987** [comment]
@fafcrumb ... great, that lets merge your branch and close the PR. @robertavram?

**Comment by adi130987** [comment]
It will be fixed by #9

**Comment by adi130987** [comment]
Fixed.
