### ISSUE TITLE
Inconsistent spelling in partner/cso types

### ISSUE THREAD

**Issue by fafcrumb** [unicef/etools-partnership-management#21]
"Organization" in Community Based Organization and Civil Society Organization is sometimes spelled
"Organisation". This is a problem for filtering. More of a data issue, but needed a reminder.

**Comment by fafcrumb** [comment]
I'll add on to this issue that "National NGO" and "National" and "International NGO" and "International" for CSO type create problems with filtering

**Comment by adi130987** [comment]
I also have this issue for the condition to show core values assessment attachement on partner details page (Show if Partner Type= CSO/National)
