### ISSUE TITLE
Add new fields to PD / SSFA details screen

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partnership-management#272]
https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016128

Things like sectors, frequency of reporting, contributing to clusters, locations etc.

**Comment by kasfaw** [comment]
Feedback related selection of reporting frequency here: https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016128/comments/82341784

Ticket may also be related to: https://github.com/unicef/etools-partner-reporting-portal/issues/45
