### ISSUE TITLE
Add "cluster indicator" yes/no and other changes to indicator modal

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partnership-management#273]
As part of this task, just focus on the "no" option of "cluster indicator"

https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016125

The "locations" would be a ones selected in PD. See #272

Section dropdown.

**Comment by kasfaw** [comment]
https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016125 

As part of this task, just focus on the "no" option of "cluster indicator". 
The "locations" would be a ones selected in PD;
 If 1 location specified for PD, then it is the default pre-populated value in the indicator modal window. 
If more than 1 is specified for PD, then the field in the modal is blank and the user will have to make a choice
Include ability to add a Section for each indicator based on sections selected for the PD
If only 1 is selected, than this is the default
If more than 1, then the field in the modal window should be blank and the user makes selection.
