### ISSUE TITLE
Enhancements for Routing

### ISSUE THREAD

**Issue by petershafer** [unicef/etools-partnership-management#33]
I've heard there are ongoing enhancements happening to routing and it sounds like others people on the team are interested in discussing them.  @robertavram, @adi130987, could either of you describe what's changing, or point us in the right direction to learn more about the changes? cc: @fafcrumb.

**Comment by robertavram** [comment]
let me loop you in... I'll reach out on slack

**Comment by petershafer** [comment]
Thanks, Rob.
