### ISSUE TITLE
Ability to select admin level and list of locations for each admin level in PD and also when editing/creating an indicator in the PD

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partnership-management#365]
See: https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016128

When editing a PD user should be able to select a list of <admin level -> [locations]>.

admin_level_1 -> [l1, l2....]
admin_level_2 -> [l3, l4, l5....]
etc.

When an admin level is selected at the PD level, then only locations within that admin level should appear. User can add / delete one or more admin levels/locations.

This way when going to define/edit an indicator user has to select one of these admin levels and the subset of locations defined. When saving a PD validations should be run in frontend and backend to make sure that the admin levels and locations selected in the indicator are valid ones that are configured in the PD as well by the user.

![image_6546160](https://user-images.githubusercontent.com/73096/27920987-358d54a4-622b-11e7-9649-df41be349698.JPG)

**Comment by kasialanecka** [comment]
@chachra I've made the change, but I pinged Evrim to check it with her.

**Comment by kasfaw** [comment]
Adding two comment threads related to this: 

https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016128/comments/81619046
https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016128/comments/81158783
