### ISSUE TITLE
Be able to provide mandatory rating of final report by partner

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-partnership-management#398]
The PO should be required to provide a rate to the final report from an IP.

The rating for the final report are: 
Met all results as planned
Constrained (partially met results) 

![image](https://user-images.githubusercontent.com/11070629/28525283-b033ad3c-7051-11e7-9bed-b24f2304cd81.png)

**Comment by mpawlowski85** [comment]
There must also be a way to rate all of the interim reports.

![image](https://user-images.githubusercontent.com/26120371/28635806-e6ff7d00-7209-11e7-9b57-38fee76a2492.png)
