### ISSUE TITLE
API questions for Government in Simple section

### ISSUE THREAD

**Issue by petershafer** [unicef/etools-partnership-management#41]
Hey guys, here are some questions I have about the API and section I'm working on.  Some of this is me still orienting to the project, but whatever help you can provide is much appreciated.

- I’m assuming that list of governments is queried from the partners indexDB (populated from api/partners.) Is this correct?
- It looks like outputs are derived from reports/results.  Do these need to be assembled into a tree structure?
- Where do I get implementation status details?  Which API endpoint can I find that at?
- Where do I get work plan results?  I’ve not found anything in the API for it.
- What is the relationship between work plan results and activities?  I thought activities mapped to outputs.

cc: @robertavram

**Comment by robertavram** [comment]
hey @petershafer .. let me try to answer:
_I’m assuming that list of governments is queried from the partners indexDB (populated from api/partners.) Is this correct?_
**that's correct**
_It looks like outputs are derived from reports/results. Do these need to be assembled into a tree structure?_
**I believe that you're only looking for the outputs.. and yes they come from Results and they are in a tree structure... but you;re only looking at the outputs**
 _Where do I get implementation status details? Which API endpoint can I find that at?_
**On the implementation status... we have to rebuild it after we get the api endpoint from the SAP guys, you can hold off for now. we can chat about it**

_Where do I get work plan results? I’ve not found anything in the API for it._
**On the workplan results we have to hold off on as well as the api endpoint is not ready yet.. however building the ui should be straightforward, individually i believe we have access to all the data to populate those fields... the main one is Result-filtered by output - let's chat tomorrow**

_What is the relationship between work plan results and activities? I thought activities mapped to outputs._
**Good question, those activities, are actually not the same as the ones mapped under Outputs. these will be inputted here for the first time**

Great questions, Looking forward to going over everything tomorrow or wednesday with you... keep the good questions coming in the meantime :)
