### ISSUE TITLE
Check and update data-table elements from etools-dashboard

### ISSUE THREAD

**Issue by adi130987** [unicef/etools-partnership-management#71]

**Comment by marko911** [comment]
## data-table-header
path : `etools-dashboard/dash/app-elements/data-table/data-table-header.html`

Added `no-title` boolean attribute on element which when present will remove the floated label title and resize the header to fit the header columns properly  ( will have same height as data-table-row for example). 

As is shown in this  [screen] (https://projects.invisionapp.com/share/MD9LN1GJB#/screens/209753932) , the data table.

## data-table-row
path: `etools-dashboard/dash/app-elements/data-table/data-table-row.html`

Added `no-collapse` attribute which when present will remove the collapsable functionality and presentational style of the element. 

The icon on the far left is removed and the padding is adjusted to properly align the columns in the remaining space. The hover effect is also removed.

**Comment by adi130987** [comment]
#76
